# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0002_auto_20180504_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('is_teacher', 'Is Teacher'), ('is_student', 'Is Student'))},
        ),
    ]
